# Generated by Django 2.2.5 on 2021-05-07 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20210409_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
